export const carsModels = {
  BMW: ['M3 GT', 'X5 M', 'M4 Coupe', 'i8', 'Z4 Roadster', 'M5 Competition', 'X7', 'M2 CS', '330i', '750Li'],
  Mercedes: [
    'AMG GT',
    'C63 AMG',
    'E-Class Coupe',
    'S500',
    'GLE Coupe',
    'A45 AMG',
    'GLS 600 Maybach',
    'SLS AMG',
    'CLA 35 AMG',
    'G-Class',
  ],
  Audi: ['RS6 Avant', 'A7 Sportback', 'R8 V10', 'Q8', 'S3 Sedan', 'TT RS', 'SQ5', 'A4 Allroad', 'RS Q8', 'A6 e-tron'],
  Ford: [
    'Mustang GT',
    'F-150 Raptor',
    'Focus RS',
    'Explorer ST',
    'Bronco',
    'GT',
    'Maverick',
    'Escape',
    'Edge ST',
    'Expedition',
  ],
  Toyota: [
    'Supra GR',
    'Camry TRD',
    'Land Cruiser',
    'Corolla GR',
    'Hilux',
    'RAV4 Prime',
    'Tacoma TRD Pro',
    'Avalon',
    'Sequoia',
    'C-HR',
  ],
  Nissan: [
    'GT-R R35',
    '370Z Nismo',
    'Skyline R34',
    'Juke Nismo',
    'Pathfinder',
    'X-Trail',
    'Qashqai',
    'Navara',
    'Murano',
    'Leaf',
  ],
  Honda: [
    'Civic Type R',
    'NSX',
    'Accord Sport',
    'CR-V Hybrid',
    'S2000',
    'Pilot',
    'Odyssey',
    'Fit',
    'Ridgeline',
    'HR-V',
  ],
  Chevrolet: [
    'Camaro ZL1',
    'Corvette C8',
    'Silverado',
    'Malibu',
    'Tahoe',
    'Suburban',
    'Blazer',
    'Traverse',
    'Equinox',
    'Colorado',
  ],
  Porsche: [
    '911 Turbo S',
    'Cayenne Turbo',
    'Panamera GTS',
    'Taycan Turbo',
    'Macan S',
    '718 Cayman GT4',
    'Carrera GT',
    'Boxster GTS',
    '911 Carrera',
    'Macan GTS',
  ],
  Tesla: [
    'Model S Plaid',
    'Model 3 Performance',
    'Model X',
    'Model Y',
    'Cybertruck',
    'Roadster',
    'Model S Long Range',
    'Model 3 Long Range',
    'Semi',
    'Model Y Standard',
  ],
  Lamborghini: [
    'Huracan EVO',
    'Aventador SVJ',
    'Urus',
    'Gallardo',
    'Murcielago',
    'Diablo',
    'Reventon',
    'Countach',
    'Sesto Elemento',
    'Centenario',
  ],
  Ferrari: [
    'SF90 Stradale',
    'F8 Tributo',
    '488 Pista',
    '812 Superfast',
    'LaFerrari',
    'Portofino',
    'GTC4Lusso',
    'Roma',
    'F430',
    'Enzo Ferrari',
  ],
  Maserati: [
    'MC20',
    'Levante',
    'Ghibli',
    'Quattroporte',
    'GranTurismo',
    'GranCabrio',
    'Alfieri',
    'Biturbo',
    'MC12',
    'Bora',
  ],
  Jaguar: ['F-Type', 'XF', 'XJ', 'E-Pace', 'F-Pace', 'I-Pace', 'XK', 'XE', 'XJR', 'D-Type'],
  Subaru: ['WRX STI', 'BRZ', 'Outback', 'Forester', 'Legacy', 'Impreza', 'Crosstrek', 'Levorg', 'Baja', 'Ascent'],
};
